name: fighting-game
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pygame==2.5.2
    - numpy==1.26.0
    - tensorflow==2.15.0
    - pillow==10.1.0
    - opencv-python==4.8.1.78 